---
- name: Ensure Redis Server is at the latest version
  sudo: yes
  apt: name=redis-server state=latest update-cache=yes
  notify:
  - restart redis

- name: Bind Redis Server to all interfaces
  sudo: yes
  lineinfile: dest=/etc/redis/redis.conf state=present regexp="^#?bind" line="#bind 127.0.0.1"
  notify:
  - restart redis

- name: Ensure Redis Server is running
  sudo: yes
  service: name=redis-server state=started
  notify:
  - restart redis
