---
- name: Adding key for NGINX repository
  sudo: true
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: Adding NGINX repository
  sudo: true
  copy: content='deb http://nginx.org/packages/mainline/debian/ wheezy nginx' dest=/etc/apt/sources.list.d/nginx.list owner=root group=root mode=644

- name: Ensure PostgreSQL 9.3 is at the latest version
  sudo: true
  apt: name={{item}} state=latest
  with_items:
    - postgresql-9.3
    - postgresql-contrib-9.3
    - postgresql-server-dev-9.3
    - python-psycopg2
  notify:
  - restart postgresql

- name: Ensure NGINX is at the latest version
  sudo: true
  apt: pkg=nginx state=latest
  notify:
  - restart nginx

- name: Create NGINX log directory
  sudo: true
  shell: mkdir -p /var/log/{{app_name}}.dev

- name: Ensure VirtualHost files exists and is updated
  sudo: true
  template: src=nginx.j2 dest=/etc/nginx/conf.d/{{app_name}}.dev.conf
  notify:
  - restart nginx

- name: Be sure NGINX is running and enabled
  sudo: true
  service: name=nginx state=running enabled=yes
